### ISSUE TITLE
Debug menu crashes the game

### ISSUE THREAD

**Issue by Leo512bit** [OpenRA/raclassic#198]
# On the latest release 
`OpenRA engine version playtest-20210131
Red Alert Classic mod version playtest-20210131
on map e048d57b300382b991d2c1afab8743bf9da198cb (Finger Lake by Westwood Studios).
Date: 2021-02-28 04:41:54Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type 'System.ArgumentException': Sprite order-icons/debug was not found.
   at OpenRA.Mods.Common.Widgets.ImageWidget.Draw()
   at OpenRA.Widgets.Widget.DrawOuter()
   at OpenRA.Widgets.Widget.DrawOuter()
   at OpenRA.Widgets.Widget.DrawOuter()
   at OpenRA.Widgets.Widget.DrawOuter()
   at OpenRA.Widgets.Widget.DrawOuter()
   at OpenRA.Widgets.Widget.DrawOuter()
   at OpenRA.Widgets.Widget.DrawOuter()
   at OpenRA.Widgets.Widget.DrawOuter()
   at OpenRA.Widgets.Widget.DrawOuter()
   at OpenRA.Game.RenderTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Game.InitializeAndRun(String[] args)
   at OpenRA.WindowsLauncher.WindowsLauncher.RunGame(String[] args)
`
# On the master 
`OpenRA engine version {DEV_VERSION}
Date: 2020-12-16 19:38:04Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.InvalidOperationException`: Unknown or invalid mod 'modcontent'.
   at OpenRA.Game.InitializeMod(String mod, Arguments args)
   at OpenRA.Mods.Common.LoadScreens.BlankLoadScreen.BeforeLoad()
   at OpenRA.Game.InitializeMod(String mod, Arguments args)
   at OpenRA.Game.Initialize(Arguments args)
   at OpenRA.Program.Run(String[] args)
   at OpenRA.Program.Main(String[] args)
`

**Comment by MustaphaTR** [comment]
This should be fixed by: https://github.com/OpenRA/raclassic/commit/d4ad540a69fc943565a7bab1e9aef2b349b5b766
