### ISSUE TITLE
Exception of type `System.NotImplementedException`: No rules definition for unit 1tnk.husk

### ISSUE THREAD

**Issue by compie** [OpenRA/raclassic#199]
OpenRA engine version playtest-20210131
Red Alert mod version playtest-20210131
on map 08017a2d5f9417f7e0b4680f0c6b14e9a7db7fab (Chernobyl 3 vs 3[LP] by Lad).
Date: 2021-03-01 20:19:53Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.NotImplementedException`: No rules definition for unit 1tnk.husk
   at OpenRA.Actor..ctor(World world, String name, TypeDictionary initDict)
   at OpenRA.Mods.Common.Traits.SpawnActorOnDeath.<>c__DisplayClass5_0.<OpenRA.Traits.INotifyRemovedFromWorld.RemovedFromWorld>b__4(World w)
   at OpenRA.World.Tick()
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   at OpenRA.Game.LogicTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Game.InitializeAndRun(String[] args)
   at OpenRA.WindowsLauncher.WindowsLauncher.RunGame(String[] args)

**Comment by MustaphaTR** [comment]
> Red Alert mod
Looks like you posted this on the wrong repo, this is RA Classic mod, looks like you are playing normal OpenRA Red Alert. And sounds like this is an issue with the map. Light Tank husk has been removed on OpenRA Red Alert recently.
